/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/* source: spywrap.i */

#define SWIGMODULE spywrap
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern char* _cgo_topofstack(void) __attribute__ ((weak));
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static char *_swig_topofstack() {
  if (_cgo_topofstack) {
    return _cgo_topofstack();
  } else {
    return 0;
  }
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } SWIGSTRUCTPACKED a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


static _gostring_ Swig_AllocateString(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)malloc(l);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


#include <stdint.h>		// Use the C99 official header


#include "airspy/airspy.h"
#include "airspy/wrap.h"


#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_spywrap_c67b9816208bfcb4(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_spywrap_c67b9816208bfcb4(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


intgo _wrap_AIRSPY_SUCCESS_spywrap_c67b9816208bfcb4() {
  enum airspy_error result;
  intgo _swig_go_result;
  
  
  result = AIRSPY_SUCCESS;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_AIRSPY_TRUE_spywrap_c67b9816208bfcb4() {
  enum airspy_error result;
  intgo _swig_go_result;
  
  
  result = AIRSPY_TRUE;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_AIRSPY_ERROR_INVALID_PARAM_spywrap_c67b9816208bfcb4() {
  enum airspy_error result;
  intgo _swig_go_result;
  
  
  result = AIRSPY_ERROR_INVALID_PARAM;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_AIRSPY_ERROR_NOT_FOUND_spywrap_c67b9816208bfcb4() {
  enum airspy_error result;
  intgo _swig_go_result;
  
  
  result = AIRSPY_ERROR_NOT_FOUND;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_AIRSPY_ERROR_BUSY_spywrap_c67b9816208bfcb4() {
  enum airspy_error result;
  intgo _swig_go_result;
  
  
  result = AIRSPY_ERROR_BUSY;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_AIRSPY_ERROR_NO_MEM_spywrap_c67b9816208bfcb4() {
  enum airspy_error result;
  intgo _swig_go_result;
  
  
  result = AIRSPY_ERROR_NO_MEM;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_AIRSPY_ERROR_LIBUSB_spywrap_c67b9816208bfcb4() {
  enum airspy_error result;
  intgo _swig_go_result;
  
  
  result = AIRSPY_ERROR_LIBUSB;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_AIRSPY_ERROR_THREAD_spywrap_c67b9816208bfcb4() {
  enum airspy_error result;
  intgo _swig_go_result;
  
  
  result = AIRSPY_ERROR_THREAD;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_AIRSPY_ERROR_STREAMING_THREAD_ERR_spywrap_c67b9816208bfcb4() {
  enum airspy_error result;
  intgo _swig_go_result;
  
  
  result = AIRSPY_ERROR_STREAMING_THREAD_ERR;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_AIRSPY_ERROR_STREAMING_STOPPED_spywrap_c67b9816208bfcb4() {
  enum airspy_error result;
  intgo _swig_go_result;
  
  
  result = AIRSPY_ERROR_STREAMING_STOPPED;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_AIRSPY_ERROR_OTHER_spywrap_c67b9816208bfcb4() {
  enum airspy_error result;
  intgo _swig_go_result;
  
  
  result = AIRSPY_ERROR_OTHER;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_AIRSPY_BOARD_ID_PROTO_AIRSPY_spywrap_c67b9816208bfcb4() {
  enum airspy_board_id result;
  intgo _swig_go_result;
  
  
  result = AIRSPY_BOARD_ID_PROTO_AIRSPY;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_AIRSPY_BOARD_ID_INVALID_spywrap_c67b9816208bfcb4() {
  enum airspy_board_id result;
  intgo _swig_go_result;
  
  
  result = AIRSPY_BOARD_ID_INVALID;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_AIRSPY_SAMPLE_FLOAT32_IQ_spywrap_c67b9816208bfcb4() {
  enum airspy_sample_type result;
  intgo _swig_go_result;
  
  
  result = AIRSPY_SAMPLE_FLOAT32_IQ;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_AIRSPY_SAMPLE_FLOAT32_REAL_spywrap_c67b9816208bfcb4() {
  enum airspy_sample_type result;
  intgo _swig_go_result;
  
  
  result = AIRSPY_SAMPLE_FLOAT32_REAL;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_AIRSPY_SAMPLE_INT16_IQ_spywrap_c67b9816208bfcb4() {
  enum airspy_sample_type result;
  intgo _swig_go_result;
  
  
  result = AIRSPY_SAMPLE_INT16_IQ;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_AIRSPY_SAMPLE_INT16_REAL_spywrap_c67b9816208bfcb4() {
  enum airspy_sample_type result;
  intgo _swig_go_result;
  
  
  result = AIRSPY_SAMPLE_INT16_REAL;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_AIRSPY_SAMPLE_UINT16_REAL_spywrap_c67b9816208bfcb4() {
  enum airspy_sample_type result;
  intgo _swig_go_result;
  
  
  result = AIRSPY_SAMPLE_UINT16_REAL;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_AIRSPY_SAMPLE_RAW_spywrap_c67b9816208bfcb4() {
  enum airspy_sample_type result;
  intgo _swig_go_result;
  
  
  result = AIRSPY_SAMPLE_RAW;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_AIRSPY_SAMPLE_END_spywrap_c67b9816208bfcb4() {
  enum airspy_sample_type result;
  intgo _swig_go_result;
  
  
  result = AIRSPY_SAMPLE_END;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_MAX_CONFIG_PAGE_SIZE_spywrap_c67b9816208bfcb4() {
  int result;
  intgo _swig_go_result;
  
  
  result = (0x10000);
  
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_airspy_transfer_t_device_set_spywrap_c67b9816208bfcb4(airspy_transfer_t *_swig_go_0, struct airspy_device *_swig_go_1) {
  airspy_transfer_t *arg1 = (airspy_transfer_t *) 0 ;
  struct airspy_device *arg2 = (struct airspy_device *) 0 ;
  
  arg1 = *(airspy_transfer_t **)&_swig_go_0; 
  arg2 = *(struct airspy_device **)&_swig_go_1; 
  
  if (arg1) (arg1)->device = arg2;
  
}


struct airspy_device *_wrap_airspy_transfer_t_device_get_spywrap_c67b9816208bfcb4(airspy_transfer_t *_swig_go_0) {
  airspy_transfer_t *arg1 = (airspy_transfer_t *) 0 ;
  struct airspy_device *result = 0 ;
  struct airspy_device *_swig_go_result;
  
  arg1 = *(airspy_transfer_t **)&_swig_go_0; 
  
  result = (struct airspy_device *) ((arg1)->device);
  *(struct airspy_device **)&_swig_go_result = (struct airspy_device *)result; 
  return _swig_go_result;
}


void _wrap_airspy_transfer_t_ctx_set_spywrap_c67b9816208bfcb4(airspy_transfer_t *_swig_go_0, void *_swig_go_1) {
  airspy_transfer_t *arg1 = (airspy_transfer_t *) 0 ;
  void *arg2 = (void *) 0 ;
  
  arg1 = *(airspy_transfer_t **)&_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  
  if (arg1) (arg1)->ctx = arg2;
  
}


void *_wrap_airspy_transfer_t_ctx_get_spywrap_c67b9816208bfcb4(airspy_transfer_t *_swig_go_0) {
  airspy_transfer_t *arg1 = (airspy_transfer_t *) 0 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(airspy_transfer_t **)&_swig_go_0; 
  
  result = (void *) ((arg1)->ctx);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void _wrap_airspy_transfer_t_samples_set_spywrap_c67b9816208bfcb4(airspy_transfer_t *_swig_go_0, void *_swig_go_1) {
  airspy_transfer_t *arg1 = (airspy_transfer_t *) 0 ;
  void *arg2 = (void *) 0 ;
  
  arg1 = *(airspy_transfer_t **)&_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  
  if (arg1) (arg1)->samples = arg2;
  
}


void *_wrap_airspy_transfer_t_samples_get_spywrap_c67b9816208bfcb4(airspy_transfer_t *_swig_go_0) {
  airspy_transfer_t *arg1 = (airspy_transfer_t *) 0 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(airspy_transfer_t **)&_swig_go_0; 
  
  result = (void *) ((arg1)->samples);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void _wrap_airspy_transfer_t_sample_count_set_spywrap_c67b9816208bfcb4(airspy_transfer_t *_swig_go_0, intgo _swig_go_1) {
  airspy_transfer_t *arg1 = (airspy_transfer_t *) 0 ;
  int arg2 ;
  
  arg1 = *(airspy_transfer_t **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->sample_count = arg2;
  
}


intgo _wrap_airspy_transfer_t_sample_count_get_spywrap_c67b9816208bfcb4(airspy_transfer_t *_swig_go_0) {
  airspy_transfer_t *arg1 = (airspy_transfer_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(airspy_transfer_t **)&_swig_go_0; 
  
  result = (int) ((arg1)->sample_count);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_airspy_transfer_t_dropped_samples_set_spywrap_c67b9816208bfcb4(airspy_transfer_t *_swig_go_0, long long _swig_go_1) {
  airspy_transfer_t *arg1 = (airspy_transfer_t *) 0 ;
  uint64_t arg2 ;
  
  arg1 = *(airspy_transfer_t **)&_swig_go_0; 
  arg2 = (uint64_t)_swig_go_1; 
  
  if (arg1) (arg1)->dropped_samples = arg2;
  
}


long long _wrap_airspy_transfer_t_dropped_samples_get_spywrap_c67b9816208bfcb4(airspy_transfer_t *_swig_go_0) {
  airspy_transfer_t *arg1 = (airspy_transfer_t *) 0 ;
  uint64_t result;
  long long _swig_go_result;
  
  arg1 = *(airspy_transfer_t **)&_swig_go_0; 
  
  result = (uint64_t) ((arg1)->dropped_samples);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_airspy_transfer_t_sample_type_set_spywrap_c67b9816208bfcb4(airspy_transfer_t *_swig_go_0, intgo _swig_go_1) {
  airspy_transfer_t *arg1 = (airspy_transfer_t *) 0 ;
  enum airspy_sample_type arg2 ;
  
  arg1 = *(airspy_transfer_t **)&_swig_go_0; 
  arg2 = (enum airspy_sample_type)_swig_go_1; 
  
  if (arg1) (arg1)->sample_type = arg2;
  
}


intgo _wrap_airspy_transfer_t_sample_type_get_spywrap_c67b9816208bfcb4(airspy_transfer_t *_swig_go_0) {
  airspy_transfer_t *arg1 = (airspy_transfer_t *) 0 ;
  enum airspy_sample_type result;
  intgo _swig_go_result;
  
  arg1 = *(airspy_transfer_t **)&_swig_go_0; 
  
  result = (enum airspy_sample_type) ((arg1)->sample_type);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


airspy_transfer_t *_wrap_new_airspy_transfer_t_spywrap_c67b9816208bfcb4() {
  airspy_transfer_t *result = 0 ;
  airspy_transfer_t *_swig_go_result;
  
  
  result = (airspy_transfer_t *)calloc(1, sizeof(airspy_transfer_t));
  *(airspy_transfer_t **)&_swig_go_result = (airspy_transfer_t *)result; 
  return _swig_go_result;
}


void _wrap_delete_airspy_transfer_t_spywrap_c67b9816208bfcb4(airspy_transfer_t *_swig_go_0) {
  airspy_transfer_t *arg1 = (airspy_transfer_t *) 0 ;
  
  arg1 = *(airspy_transfer_t **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


void _wrap_airspy_read_partid_serialno_t_part_id_set_spywrap_c67b9816208bfcb4(airspy_read_partid_serialno_t *_swig_go_0, intgo *_swig_go_1) {
  airspy_read_partid_serialno_t *arg1 = (airspy_read_partid_serialno_t *) 0 ;
  uint32_t *arg2 ;
  
  arg1 = *(airspy_read_partid_serialno_t **)&_swig_go_0; 
  arg2 = *(uint32_t **)&_swig_go_1; 
  
  {
    size_t ii;
    uint32_t *b = (uint32_t *) arg1->part_id;
    for (ii = 0; ii < (size_t)2; ii++) b[ii] = *((uint32_t *) arg2 + ii);
  }
  
}


intgo *_wrap_airspy_read_partid_serialno_t_part_id_get_spywrap_c67b9816208bfcb4(airspy_read_partid_serialno_t *_swig_go_0) {
  airspy_read_partid_serialno_t *arg1 = (airspy_read_partid_serialno_t *) 0 ;
  uint32_t *result = 0 ;
  intgo *_swig_go_result;
  
  arg1 = *(airspy_read_partid_serialno_t **)&_swig_go_0; 
  
  result = (uint32_t *)(uint32_t *) ((arg1)->part_id);
  *(uint32_t **)&_swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_airspy_read_partid_serialno_t_serial_no_set_spywrap_c67b9816208bfcb4(airspy_read_partid_serialno_t *_swig_go_0, intgo *_swig_go_1) {
  airspy_read_partid_serialno_t *arg1 = (airspy_read_partid_serialno_t *) 0 ;
  uint32_t *arg2 ;
  
  arg1 = *(airspy_read_partid_serialno_t **)&_swig_go_0; 
  arg2 = *(uint32_t **)&_swig_go_1; 
  
  {
    size_t ii;
    uint32_t *b = (uint32_t *) arg1->serial_no;
    for (ii = 0; ii < (size_t)4; ii++) b[ii] = *((uint32_t *) arg2 + ii);
  }
  
}


intgo *_wrap_airspy_read_partid_serialno_t_serial_no_get_spywrap_c67b9816208bfcb4(airspy_read_partid_serialno_t *_swig_go_0) {
  airspy_read_partid_serialno_t *arg1 = (airspy_read_partid_serialno_t *) 0 ;
  uint32_t *result = 0 ;
  intgo *_swig_go_result;
  
  arg1 = *(airspy_read_partid_serialno_t **)&_swig_go_0; 
  
  result = (uint32_t *)(uint32_t *) ((arg1)->serial_no);
  *(uint32_t **)&_swig_go_result = result; 
  return _swig_go_result;
}


airspy_read_partid_serialno_t *_wrap_new_airspy_read_partid_serialno_t_spywrap_c67b9816208bfcb4() {
  airspy_read_partid_serialno_t *result = 0 ;
  airspy_read_partid_serialno_t *_swig_go_result;
  
  
  result = (airspy_read_partid_serialno_t *)calloc(1, sizeof(airspy_read_partid_serialno_t));
  *(airspy_read_partid_serialno_t **)&_swig_go_result = (airspy_read_partid_serialno_t *)result; 
  return _swig_go_result;
}


void _wrap_delete_airspy_read_partid_serialno_t_spywrap_c67b9816208bfcb4(airspy_read_partid_serialno_t *_swig_go_0) {
  airspy_read_partid_serialno_t *arg1 = (airspy_read_partid_serialno_t *) 0 ;
  
  arg1 = *(airspy_read_partid_serialno_t **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


void _wrap_airspy_lib_version_t_major_version_set_spywrap_c67b9816208bfcb4(airspy_lib_version_t *_swig_go_0, intgo _swig_go_1) {
  airspy_lib_version_t *arg1 = (airspy_lib_version_t *) 0 ;
  uint32_t arg2 ;
  
  arg1 = *(airspy_lib_version_t **)&_swig_go_0; 
  arg2 = (uint32_t)_swig_go_1; 
  
  if (arg1) (arg1)->major_version = arg2;
  
}


intgo _wrap_airspy_lib_version_t_major_version_get_spywrap_c67b9816208bfcb4(airspy_lib_version_t *_swig_go_0) {
  airspy_lib_version_t *arg1 = (airspy_lib_version_t *) 0 ;
  uint32_t result;
  intgo _swig_go_result;
  
  arg1 = *(airspy_lib_version_t **)&_swig_go_0; 
  
  result = (uint32_t) ((arg1)->major_version);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_airspy_lib_version_t_minor_version_set_spywrap_c67b9816208bfcb4(airspy_lib_version_t *_swig_go_0, intgo _swig_go_1) {
  airspy_lib_version_t *arg1 = (airspy_lib_version_t *) 0 ;
  uint32_t arg2 ;
  
  arg1 = *(airspy_lib_version_t **)&_swig_go_0; 
  arg2 = (uint32_t)_swig_go_1; 
  
  if (arg1) (arg1)->minor_version = arg2;
  
}


intgo _wrap_airspy_lib_version_t_minor_version_get_spywrap_c67b9816208bfcb4(airspy_lib_version_t *_swig_go_0) {
  airspy_lib_version_t *arg1 = (airspy_lib_version_t *) 0 ;
  uint32_t result;
  intgo _swig_go_result;
  
  arg1 = *(airspy_lib_version_t **)&_swig_go_0; 
  
  result = (uint32_t) ((arg1)->minor_version);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_airspy_lib_version_t_revision_set_spywrap_c67b9816208bfcb4(airspy_lib_version_t *_swig_go_0, intgo _swig_go_1) {
  airspy_lib_version_t *arg1 = (airspy_lib_version_t *) 0 ;
  uint32_t arg2 ;
  
  arg1 = *(airspy_lib_version_t **)&_swig_go_0; 
  arg2 = (uint32_t)_swig_go_1; 
  
  if (arg1) (arg1)->revision = arg2;
  
}


intgo _wrap_airspy_lib_version_t_revision_get_spywrap_c67b9816208bfcb4(airspy_lib_version_t *_swig_go_0) {
  airspy_lib_version_t *arg1 = (airspy_lib_version_t *) 0 ;
  uint32_t result;
  intgo _swig_go_result;
  
  arg1 = *(airspy_lib_version_t **)&_swig_go_0; 
  
  result = (uint32_t) ((arg1)->revision);
  _swig_go_result = result; 
  return _swig_go_result;
}


airspy_lib_version_t *_wrap_new_airspy_lib_version_t_spywrap_c67b9816208bfcb4() {
  airspy_lib_version_t *result = 0 ;
  airspy_lib_version_t *_swig_go_result;
  
  
  result = (airspy_lib_version_t *)calloc(1, sizeof(airspy_lib_version_t));
  *(airspy_lib_version_t **)&_swig_go_result = (airspy_lib_version_t *)result; 
  return _swig_go_result;
}


void _wrap_delete_airspy_lib_version_t_spywrap_c67b9816208bfcb4(airspy_lib_version_t *_swig_go_0) {
  airspy_lib_version_t *arg1 = (airspy_lib_version_t *) 0 ;
  
  arg1 = *(airspy_lib_version_t **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


void _wrap_airspy_lib_version_spywrap_c67b9816208bfcb4(airspy_lib_version_t *_swig_go_0) {
  airspy_lib_version_t *arg1 = (airspy_lib_version_t *) 0 ;
  
  arg1 = *(airspy_lib_version_t **)&_swig_go_0; 
  
  airspy_lib_version(arg1);
  
}


intgo _wrap_airspy_init_spywrap_c67b9816208bfcb4() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)airspy_init();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_exit_spywrap_c67b9816208bfcb4() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)airspy_exit();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_open_sn_spywrap_c67b9816208bfcb4(struct airspy_device **_swig_go_0, long long _swig_go_1) {
  struct airspy_device **arg1 = (struct airspy_device **) 0 ;
  uint64_t arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device ***)&_swig_go_0; 
  arg2 = (uint64_t)_swig_go_1; 
  
  result = (int)airspy_open_sn(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_open_spywrap_c67b9816208bfcb4(struct airspy_device **_swig_go_0) {
  struct airspy_device **arg1 = (struct airspy_device **) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device ***)&_swig_go_0; 
  
  result = (int)airspy_open(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_close_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  
  result = (int)airspy_close(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_get_samplerates_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, _goslice_ _swig_go_1, intgo _swig_go_2) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  uint32_t *arg2 = (uint32_t *) 0 ;
  uint32_t arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  arg2 = *(uint32_t **)&_swig_go_1; 
  arg3 = (uint32_t)_swig_go_2; 
  
  result = (int)airspy_get_samplerates(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_set_samplerate_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, intgo _swig_go_1) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  uint32_t arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  arg2 = (uint32_t)_swig_go_1; 
  
  result = (int)airspy_set_samplerate(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_set_conversion_filter_float32_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, float *_swig_go_1, intgo _swig_go_2) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  float *arg2 = (float *) 0 ;
  uint32_t arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  arg2 = *(float **)&_swig_go_1; 
  arg3 = (uint32_t)_swig_go_2; 
  
  result = (int)airspy_set_conversion_filter_float32(arg1,(float const *)arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_set_conversion_filter_int16_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, short *_swig_go_1, intgo _swig_go_2) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  int16_t *arg2 = (int16_t *) 0 ;
  uint32_t arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  arg2 = *(int16_t **)&_swig_go_1; 
  arg3 = (uint32_t)_swig_go_2; 
  
  result = (int)airspy_set_conversion_filter_int16(arg1,(short const *)arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_start_rx_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, void** _swig_go_1, void *_swig_go_2) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  airspy_sample_block_cb_fn arg2 = (airspy_sample_block_cb_fn) 0 ;
  void *arg3 = (void *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  arg2 = *(airspy_sample_block_cb_fn *)&_swig_go_1; 
  arg3 = *(void **)&_swig_go_2; 
  
  result = (int)airspy_start_rx(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_stop_rx_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  
  result = (int)airspy_stop_rx(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_is_streaming_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  
  result = (int)airspy_is_streaming(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_si5351c_write_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, char _swig_go_1, char _swig_go_2) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  uint8_t arg2 ;
  uint8_t arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  arg2 = (uint8_t)_swig_go_1; 
  arg3 = (uint8_t)_swig_go_2; 
  
  result = (int)airspy_si5351c_write(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_si5351c_read_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, char _swig_go_1, _goslice_ _swig_go_2) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  uint8_t arg2 ;
  uint8_t *arg3 = (uint8_t *) 0 ;
  uint8_t temp3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  arg2 = (uint8_t)_swig_go_1; 
  {
    if (_swig_go_2.len == 0) {
      _swig_gopanic("array must contain at least 1 element");
    }
    arg3 = &temp3;
  }
  
  result = (int)airspy_si5351c_read(arg1,arg2,arg3);
  _swig_go_result = result; 
  {
    unsigned char* a = (unsigned char *) _swig_go_2.array;
    a[0] = temp3;
  }
  
  return _swig_go_result;
}


intgo _wrap_airspy_r820t_write_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, char _swig_go_1, char _swig_go_2) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  uint8_t arg2 ;
  uint8_t arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  arg2 = (uint8_t)_swig_go_1; 
  arg3 = (uint8_t)_swig_go_2; 
  
  result = (int)airspy_r820t_write(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_r820t_read_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, char _swig_go_1, _goslice_ _swig_go_2) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  uint8_t arg2 ;
  uint8_t *arg3 = (uint8_t *) 0 ;
  uint8_t temp3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  arg2 = (uint8_t)_swig_go_1; 
  {
    if (_swig_go_2.len == 0) {
      _swig_gopanic("array must contain at least 1 element");
    }
    arg3 = &temp3;
  }
  
  result = (int)airspy_r820t_read(arg1,arg2,arg3);
  _swig_go_result = result; 
  {
    unsigned char* a = (unsigned char *) _swig_go_2.array;
    a[0] = temp3;
  }
  
  return _swig_go_result;
}


intgo _wrap_airspy_gpio_write_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, airspy_gpio_port_t *_swig_go_1, airspy_gpio_pin_t *_swig_go_2, char _swig_go_3) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  airspy_gpio_port_t arg2 ;
  airspy_gpio_pin_t arg3 ;
  uint8_t arg4 ;
  airspy_gpio_port_t *argp2 ;
  airspy_gpio_pin_t *argp3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  
  argp2 = (airspy_gpio_port_t *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null airspy_gpio_port_t");
  }
  arg2 = (airspy_gpio_port_t)*argp2;
  
  
  argp3 = (airspy_gpio_pin_t *)_swig_go_2;
  if (argp3 == NULL) {
    _swig_gopanic("Attempt to dereference null airspy_gpio_pin_t");
  }
  arg3 = (airspy_gpio_pin_t)*argp3;
  
  arg4 = (uint8_t)_swig_go_3; 
  
  result = (int)airspy_gpio_write(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_gpio_read_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, airspy_gpio_port_t *_swig_go_1, airspy_gpio_pin_t *_swig_go_2, _goslice_ _swig_go_3) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  airspy_gpio_port_t arg2 ;
  airspy_gpio_pin_t arg3 ;
  uint8_t *arg4 = (uint8_t *) 0 ;
  airspy_gpio_port_t *argp2 ;
  airspy_gpio_pin_t *argp3 ;
  uint8_t temp4 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  
  argp2 = (airspy_gpio_port_t *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null airspy_gpio_port_t");
  }
  arg2 = (airspy_gpio_port_t)*argp2;
  
  
  argp3 = (airspy_gpio_pin_t *)_swig_go_2;
  if (argp3 == NULL) {
    _swig_gopanic("Attempt to dereference null airspy_gpio_pin_t");
  }
  arg3 = (airspy_gpio_pin_t)*argp3;
  
  {
    if (_swig_go_3.len == 0) {
      _swig_gopanic("array must contain at least 1 element");
    }
    arg4 = &temp4;
  }
  
  result = (int)airspy_gpio_read(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  {
    unsigned char* a = (unsigned char *) _swig_go_3.array;
    a[0] = temp4;
  }
  
  return _swig_go_result;
}


intgo _wrap_airspy_gpiodir_write_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, airspy_gpio_port_t *_swig_go_1, airspy_gpio_pin_t *_swig_go_2, char _swig_go_3) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  airspy_gpio_port_t arg2 ;
  airspy_gpio_pin_t arg3 ;
  uint8_t arg4 ;
  airspy_gpio_port_t *argp2 ;
  airspy_gpio_pin_t *argp3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  
  argp2 = (airspy_gpio_port_t *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null airspy_gpio_port_t");
  }
  arg2 = (airspy_gpio_port_t)*argp2;
  
  
  argp3 = (airspy_gpio_pin_t *)_swig_go_2;
  if (argp3 == NULL) {
    _swig_gopanic("Attempt to dereference null airspy_gpio_pin_t");
  }
  arg3 = (airspy_gpio_pin_t)*argp3;
  
  arg4 = (uint8_t)_swig_go_3; 
  
  result = (int)airspy_gpiodir_write(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_gpiodir_read_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, airspy_gpio_port_t *_swig_go_1, airspy_gpio_pin_t *_swig_go_2, _goslice_ _swig_go_3) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  airspy_gpio_port_t arg2 ;
  airspy_gpio_pin_t arg3 ;
  uint8_t *arg4 = (uint8_t *) 0 ;
  airspy_gpio_port_t *argp2 ;
  airspy_gpio_pin_t *argp3 ;
  uint8_t temp4 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  
  argp2 = (airspy_gpio_port_t *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null airspy_gpio_port_t");
  }
  arg2 = (airspy_gpio_port_t)*argp2;
  
  
  argp3 = (airspy_gpio_pin_t *)_swig_go_2;
  if (argp3 == NULL) {
    _swig_gopanic("Attempt to dereference null airspy_gpio_pin_t");
  }
  arg3 = (airspy_gpio_pin_t)*argp3;
  
  {
    if (_swig_go_3.len == 0) {
      _swig_gopanic("array must contain at least 1 element");
    }
    arg4 = &temp4;
  }
  
  result = (int)airspy_gpiodir_read(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  {
    unsigned char* a = (unsigned char *) _swig_go_3.array;
    a[0] = temp4;
  }
  
  return _swig_go_result;
}


intgo _wrap_airspy_spiflash_erase_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  
  result = (int)airspy_spiflash_erase(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_spiflash_write_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, intgo _swig_go_1, short _swig_go_2, char *_swig_go_3) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  uint32_t arg2 ;
  uint16_t arg3 ;
  unsigned char *arg4 = (unsigned char *) (unsigned char *)0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  arg2 = (uint32_t)_swig_go_1; 
  arg3 = (uint16_t)_swig_go_2; 
  arg4 = *(unsigned char **)&_swig_go_3; 
  
  result = (int)airspy_spiflash_write(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_spiflash_read_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, intgo _swig_go_1, short _swig_go_2, char *_swig_go_3) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  uint32_t arg2 ;
  uint16_t arg3 ;
  unsigned char *arg4 = (unsigned char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  arg2 = (uint32_t)_swig_go_1; 
  arg3 = (uint16_t)_swig_go_2; 
  arg4 = *(unsigned char **)&_swig_go_3; 
  
  result = (int)airspy_spiflash_read(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_board_id_read_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, _goslice_ _swig_go_1) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  uint8_t temp2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  {
    if (_swig_go_1.len == 0) {
      _swig_gopanic("array must contain at least 1 element");
    }
    arg2 = &temp2;
  }
  
  result = (int)airspy_board_id_read(arg1,arg2);
  _swig_go_result = result; 
  {
    unsigned char* a = (unsigned char *) _swig_go_1.array;
    a[0] = temp2;
  }
  
  return _swig_go_result;
}


intgo _wrap_airspy_version_string_read_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, _goslice_ _swig_go_1, char _swig_go_2) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  char *arg2 = (char *) 0 ;
  uint8_t arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  {
    if (_swig_go_1.len == 0) {
      _swig_gopanic("array must contain at least 1 element");
    }
    arg2 = (char *) _swig_go_1.array;
  }
  arg3 = (uint8_t)_swig_go_2; 
  
  result = (int)airspy_version_string_read(arg1,arg2,arg3);
  _swig_go_result = result; 
  
  
  return _swig_go_result;
}


intgo _wrap_airspy_board_partid_serialno_read_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, airspy_read_partid_serialno_t *_swig_go_1) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  airspy_read_partid_serialno_t *arg2 = (airspy_read_partid_serialno_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  arg2 = *(airspy_read_partid_serialno_t **)&_swig_go_1; 
  
  result = (int)airspy_board_partid_serialno_read(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_set_sample_type_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, intgo _swig_go_1) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  enum airspy_sample_type arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  arg2 = (enum airspy_sample_type)_swig_go_1; 
  
  result = (int)airspy_set_sample_type(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_set_freq_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, intgo _swig_go_1) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  uint32_t arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  arg2 = (uint32_t)_swig_go_1; 
  
  result = (int)airspy_set_freq(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_set_lna_gain_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, char _swig_go_1) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  uint8_t arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  arg2 = (uint8_t)_swig_go_1; 
  
  result = (int)airspy_set_lna_gain(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_set_mixer_gain_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, char _swig_go_1) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  uint8_t arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  arg2 = (uint8_t)_swig_go_1; 
  
  result = (int)airspy_set_mixer_gain(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_set_vga_gain_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, char _swig_go_1) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  uint8_t arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  arg2 = (uint8_t)_swig_go_1; 
  
  result = (int)airspy_set_vga_gain(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_set_lna_agc_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, char _swig_go_1) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  uint8_t arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  arg2 = (uint8_t)_swig_go_1; 
  
  result = (int)airspy_set_lna_agc(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_set_mixer_agc_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, char _swig_go_1) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  uint8_t arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  arg2 = (uint8_t)_swig_go_1; 
  
  result = (int)airspy_set_mixer_agc(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_set_linearity_gain_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, char _swig_go_1) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  uint8_t arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  arg2 = (uint8_t)_swig_go_1; 
  
  result = (int)airspy_set_linearity_gain(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_set_sensitivity_gain_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, char _swig_go_1) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  uint8_t arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  arg2 = (uint8_t)_swig_go_1; 
  
  result = (int)airspy_set_sensitivity_gain(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_set_rf_bias_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, char _swig_go_1) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  uint8_t arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  arg2 = (uint8_t)_swig_go_1; 
  
  result = (int)airspy_set_rf_bias(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_airspy_set_packing_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, char _swig_go_1) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  uint8_t arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  arg2 = (uint8_t)_swig_go_1; 
  
  result = (int)airspy_set_packing(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


_gostring_ _wrap_airspy_error_name_spywrap_c67b9816208bfcb4(intgo _swig_go_0) {
  enum airspy_error arg1 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = (enum airspy_error)_swig_go_0; 
  
  result = (char *)airspy_error_name(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


_gostring_ _wrap_airspy_board_id_name_spywrap_c67b9816208bfcb4(intgo _swig_go_0) {
  enum airspy_board_id arg1 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = (enum airspy_board_id)_swig_go_0; 
  
  result = (char *)airspy_board_id_name(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_airspy_spiflash_erase_sector_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, short _swig_go_1) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  uint16_t arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  arg2 = (uint16_t)_swig_go_1; 
  
  result = (int)airspy_spiflash_erase_sector(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_cbProxy_spywrap_c67b9816208bfcb4(void *_swig_go_0, struct airspy_transfer_t *_swig_go_1) {
  void *arg1 = (void *) 0 ;
  airspy_transfer *arg2 = (airspy_transfer *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = *(airspy_transfer **)&_swig_go_1; 
  
  result = (int)cbProxy(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_airspy_open_result_t_device_set_spywrap_c67b9816208bfcb4(airspy_open_result_t *_swig_go_0, struct airspy_device *_swig_go_1) {
  airspy_open_result_t *arg1 = (airspy_open_result_t *) 0 ;
  struct airspy_device *arg2 = (struct airspy_device *) 0 ;
  
  arg1 = *(airspy_open_result_t **)&_swig_go_0; 
  arg2 = *(struct airspy_device **)&_swig_go_1; 
  
  if (arg1) (arg1)->device = arg2;
  
}


struct airspy_device *_wrap_airspy_open_result_t_device_get_spywrap_c67b9816208bfcb4(airspy_open_result_t *_swig_go_0) {
  airspy_open_result_t *arg1 = (airspy_open_result_t *) 0 ;
  struct airspy_device *result = 0 ;
  struct airspy_device *_swig_go_result;
  
  arg1 = *(airspy_open_result_t **)&_swig_go_0; 
  
  result = (struct airspy_device *) ((arg1)->device);
  *(struct airspy_device **)&_swig_go_result = (struct airspy_device *)result; 
  return _swig_go_result;
}


void _wrap_airspy_open_result_t_result_set_spywrap_c67b9816208bfcb4(airspy_open_result_t *_swig_go_0, intgo _swig_go_1) {
  airspy_open_result_t *arg1 = (airspy_open_result_t *) 0 ;
  int arg2 ;
  
  arg1 = *(airspy_open_result_t **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->result = arg2;
  
}


intgo _wrap_airspy_open_result_t_result_get_spywrap_c67b9816208bfcb4(airspy_open_result_t *_swig_go_0) {
  airspy_open_result_t *arg1 = (airspy_open_result_t *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(airspy_open_result_t **)&_swig_go_0; 
  
  result = (int) ((arg1)->result);
  _swig_go_result = result; 
  return _swig_go_result;
}


airspy_open_result_t *_wrap_new_airspy_open_result_t_spywrap_c67b9816208bfcb4() {
  airspy_open_result_t *result = 0 ;
  airspy_open_result_t *_swig_go_result;
  
  
  result = (airspy_open_result_t *)calloc(1, sizeof(airspy_open_result_t));
  *(airspy_open_result_t **)&_swig_go_result = (airspy_open_result_t *)result; 
  return _swig_go_result;
}


void _wrap_delete_airspy_open_result_t_spywrap_c67b9816208bfcb4(airspy_open_result_t *_swig_go_0) {
  airspy_open_result_t *arg1 = (airspy_open_result_t *) 0 ;
  
  arg1 = *(airspy_open_result_t **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


airspy_open_result_t *_wrap_openDevice_spywrap_c67b9816208bfcb4() {
  airspy_open_result_t *result = 0 ;
  airspy_open_result_t *_swig_go_result;
  
  
  result = (airspy_open_result_t *)openDevice();
  *(airspy_open_result_t **)&_swig_go_result = (airspy_open_result_t *)result; 
  return _swig_go_result;
}


airspy_open_result_t *_wrap_openDeviceBySerial_spywrap_c67b9816208bfcb4(long long _swig_go_0) {
  uint64_t arg1 ;
  airspy_open_result_t *result = 0 ;
  airspy_open_result_t *_swig_go_result;
  
  arg1 = (uint64_t)_swig_go_0; 
  
  result = (airspy_open_result_t *)openDeviceBySerial(arg1);
  *(airspy_open_result_t **)&_swig_go_result = (airspy_open_result_t *)result; 
  return _swig_go_result;
}


long long _wrap_serialNumber_spywrap_c67b9816208bfcb4(intgo *_swig_go_0) {
  uint32_t *arg1 = (uint32_t *) 0 ;
  uint64_t result;
  long long _swig_go_result;
  
  arg1 = *(uint32_t **)&_swig_go_0; 
  
  result = (uint64_t)serialNumber(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_partNumber_spywrap_c67b9816208bfcb4(intgo *_swig_go_0) {
  uint32_t *arg1 = (uint32_t *) 0 ;
  uint64_t result;
  long long _swig_go_result;
  
  arg1 = *(uint32_t **)&_swig_go_0; 
  
  result = (uint64_t)partNumber(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_freeOpenResult_spywrap_c67b9816208bfcb4(airspy_open_result_t *_swig_go_0) {
  airspy_open_result_t *arg1 = (airspy_open_result_t *) 0 ;
  
  arg1 = *(airspy_open_result_t **)&_swig_go_0; 
  
  freeOpenResult(arg1);
  
}


intgo _wrap_airspyStart_spywrap_c67b9816208bfcb4(struct airspy_device *_swig_go_0, void *_swig_go_1) {
  struct airspy_device *arg1 = (struct airspy_device *) 0 ;
  void *arg2 = (void *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct airspy_device **)&_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  
  result = (int)airspyStart(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


#ifdef __cplusplus
}
#endif

