/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: spywrap.i

package spywrap

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;



#cgo LDFLAGS: -lairspy

typedef long long swig_type_1;
typedef long long swig_type_2;
typedef long long swig_type_3;
typedef _goslice_ swig_type_4;
typedef _goslice_ swig_type_5;
typedef _goslice_ swig_type_6;
typedef _goslice_ swig_type_7;
typedef _goslice_ swig_type_8;
typedef _goslice_ swig_type_9;
typedef _goslice_ swig_type_10;
typedef _gostring_ swig_type_11;
typedef _gostring_ swig_type_12;
typedef long long swig_type_13;
typedef long long swig_type_14;
typedef long long swig_type_15;
extern void _wrap_Swig_free_spywrap_c67b9816208bfcb4(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_spywrap_c67b9816208bfcb4(swig_intgo arg1);
extern swig_intgo _wrap_AIRSPY_SUCCESS_spywrap_c67b9816208bfcb4(void);
extern swig_intgo _wrap_AIRSPY_TRUE_spywrap_c67b9816208bfcb4(void);
extern swig_intgo _wrap_AIRSPY_ERROR_INVALID_PARAM_spywrap_c67b9816208bfcb4(void);
extern swig_intgo _wrap_AIRSPY_ERROR_NOT_FOUND_spywrap_c67b9816208bfcb4(void);
extern swig_intgo _wrap_AIRSPY_ERROR_BUSY_spywrap_c67b9816208bfcb4(void);
extern swig_intgo _wrap_AIRSPY_ERROR_NO_MEM_spywrap_c67b9816208bfcb4(void);
extern swig_intgo _wrap_AIRSPY_ERROR_LIBUSB_spywrap_c67b9816208bfcb4(void);
extern swig_intgo _wrap_AIRSPY_ERROR_THREAD_spywrap_c67b9816208bfcb4(void);
extern swig_intgo _wrap_AIRSPY_ERROR_STREAMING_THREAD_ERR_spywrap_c67b9816208bfcb4(void);
extern swig_intgo _wrap_AIRSPY_ERROR_STREAMING_STOPPED_spywrap_c67b9816208bfcb4(void);
extern swig_intgo _wrap_AIRSPY_ERROR_OTHER_spywrap_c67b9816208bfcb4(void);
extern swig_intgo _wrap_AIRSPY_BOARD_ID_PROTO_AIRSPY_spywrap_c67b9816208bfcb4(void);
extern swig_intgo _wrap_AIRSPY_BOARD_ID_INVALID_spywrap_c67b9816208bfcb4(void);
extern swig_intgo _wrap_AIRSPY_SAMPLE_FLOAT32_IQ_spywrap_c67b9816208bfcb4(void);
extern swig_intgo _wrap_AIRSPY_SAMPLE_FLOAT32_REAL_spywrap_c67b9816208bfcb4(void);
extern swig_intgo _wrap_AIRSPY_SAMPLE_INT16_IQ_spywrap_c67b9816208bfcb4(void);
extern swig_intgo _wrap_AIRSPY_SAMPLE_INT16_REAL_spywrap_c67b9816208bfcb4(void);
extern swig_intgo _wrap_AIRSPY_SAMPLE_UINT16_REAL_spywrap_c67b9816208bfcb4(void);
extern swig_intgo _wrap_AIRSPY_SAMPLE_RAW_spywrap_c67b9816208bfcb4(void);
extern swig_intgo _wrap_AIRSPY_SAMPLE_END_spywrap_c67b9816208bfcb4(void);
extern swig_intgo _wrap_MAX_CONFIG_PAGE_SIZE_spywrap_c67b9816208bfcb4(void);
extern void _wrap_airspy_transfer_t_device_set_spywrap_c67b9816208bfcb4(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_airspy_transfer_t_device_get_spywrap_c67b9816208bfcb4(uintptr_t arg1);
extern void _wrap_airspy_transfer_t_ctx_set_spywrap_c67b9816208bfcb4(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_airspy_transfer_t_ctx_get_spywrap_c67b9816208bfcb4(uintptr_t arg1);
extern void _wrap_airspy_transfer_t_samples_set_spywrap_c67b9816208bfcb4(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_airspy_transfer_t_samples_get_spywrap_c67b9816208bfcb4(uintptr_t arg1);
extern void _wrap_airspy_transfer_t_sample_count_set_spywrap_c67b9816208bfcb4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_airspy_transfer_t_sample_count_get_spywrap_c67b9816208bfcb4(uintptr_t arg1);
extern void _wrap_airspy_transfer_t_dropped_samples_set_spywrap_c67b9816208bfcb4(uintptr_t arg1, swig_type_1 arg2);
extern swig_type_2 _wrap_airspy_transfer_t_dropped_samples_get_spywrap_c67b9816208bfcb4(uintptr_t arg1);
extern void _wrap_airspy_transfer_t_sample_type_set_spywrap_c67b9816208bfcb4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_airspy_transfer_t_sample_type_get_spywrap_c67b9816208bfcb4(uintptr_t arg1);
extern uintptr_t _wrap_new_airspy_transfer_t_spywrap_c67b9816208bfcb4(void);
extern void _wrap_delete_airspy_transfer_t_spywrap_c67b9816208bfcb4(uintptr_t arg1);
extern void _wrap_airspy_read_partid_serialno_t_part_id_set_spywrap_c67b9816208bfcb4(uintptr_t arg1, swig_voidp arg2);
extern swig_voidp _wrap_airspy_read_partid_serialno_t_part_id_get_spywrap_c67b9816208bfcb4(uintptr_t arg1);
extern void _wrap_airspy_read_partid_serialno_t_serial_no_set_spywrap_c67b9816208bfcb4(uintptr_t arg1, swig_voidp arg2);
extern swig_voidp _wrap_airspy_read_partid_serialno_t_serial_no_get_spywrap_c67b9816208bfcb4(uintptr_t arg1);
extern uintptr_t _wrap_new_airspy_read_partid_serialno_t_spywrap_c67b9816208bfcb4(void);
extern void _wrap_delete_airspy_read_partid_serialno_t_spywrap_c67b9816208bfcb4(uintptr_t arg1);
extern void _wrap_airspy_lib_version_t_major_version_set_spywrap_c67b9816208bfcb4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_airspy_lib_version_t_major_version_get_spywrap_c67b9816208bfcb4(uintptr_t arg1);
extern void _wrap_airspy_lib_version_t_minor_version_set_spywrap_c67b9816208bfcb4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_airspy_lib_version_t_minor_version_get_spywrap_c67b9816208bfcb4(uintptr_t arg1);
extern void _wrap_airspy_lib_version_t_revision_set_spywrap_c67b9816208bfcb4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_airspy_lib_version_t_revision_get_spywrap_c67b9816208bfcb4(uintptr_t arg1);
extern uintptr_t _wrap_new_airspy_lib_version_t_spywrap_c67b9816208bfcb4(void);
extern void _wrap_delete_airspy_lib_version_t_spywrap_c67b9816208bfcb4(uintptr_t arg1);
extern void _wrap_airspy_lib_version_spywrap_c67b9816208bfcb4(uintptr_t arg1);
extern swig_intgo _wrap_airspy_init_spywrap_c67b9816208bfcb4(void);
extern swig_intgo _wrap_airspy_exit_spywrap_c67b9816208bfcb4(void);
extern swig_intgo _wrap_airspy_open_sn_spywrap_c67b9816208bfcb4(uintptr_t arg1, swig_type_3 arg2);
extern swig_intgo _wrap_airspy_open_spywrap_c67b9816208bfcb4(uintptr_t arg1);
extern swig_intgo _wrap_airspy_close_spywrap_c67b9816208bfcb4(uintptr_t arg1);
extern swig_intgo _wrap_airspy_get_samplerates_spywrap_c67b9816208bfcb4(uintptr_t arg1, swig_type_4 arg2, swig_intgo arg3);
extern swig_intgo _wrap_airspy_set_samplerate_spywrap_c67b9816208bfcb4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_airspy_set_conversion_filter_float32_spywrap_c67b9816208bfcb4(uintptr_t arg1, swig_voidp arg2, swig_intgo arg3);
extern swig_intgo _wrap_airspy_set_conversion_filter_int16_spywrap_c67b9816208bfcb4(uintptr_t arg1, swig_voidp arg2, swig_intgo arg3);
extern swig_intgo _wrap_airspy_start_rx_spywrap_c67b9816208bfcb4(uintptr_t arg1, swig_voidp arg2, uintptr_t arg3);
extern swig_intgo _wrap_airspy_stop_rx_spywrap_c67b9816208bfcb4(uintptr_t arg1);
extern swig_intgo _wrap_airspy_is_streaming_spywrap_c67b9816208bfcb4(uintptr_t arg1);
extern swig_intgo _wrap_airspy_si5351c_write_spywrap_c67b9816208bfcb4(uintptr_t arg1, char arg2, char arg3);
extern swig_intgo _wrap_airspy_si5351c_read_spywrap_c67b9816208bfcb4(uintptr_t arg1, char arg2, swig_type_5 arg3);
extern swig_intgo _wrap_airspy_r820t_write_spywrap_c67b9816208bfcb4(uintptr_t arg1, char arg2, char arg3);
extern swig_intgo _wrap_airspy_r820t_read_spywrap_c67b9816208bfcb4(uintptr_t arg1, char arg2, swig_type_6 arg3);
extern swig_intgo _wrap_airspy_gpio_write_spywrap_c67b9816208bfcb4(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, char arg4);
extern swig_intgo _wrap_airspy_gpio_read_spywrap_c67b9816208bfcb4(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, swig_type_7 arg4);
extern swig_intgo _wrap_airspy_gpiodir_write_spywrap_c67b9816208bfcb4(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, char arg4);
extern swig_intgo _wrap_airspy_gpiodir_read_spywrap_c67b9816208bfcb4(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, swig_type_8 arg4);
extern swig_intgo _wrap_airspy_spiflash_erase_spywrap_c67b9816208bfcb4(uintptr_t arg1);
extern swig_intgo _wrap_airspy_spiflash_write_spywrap_c67b9816208bfcb4(uintptr_t arg1, swig_intgo arg2, short arg3, swig_voidp arg4);
extern swig_intgo _wrap_airspy_spiflash_read_spywrap_c67b9816208bfcb4(uintptr_t arg1, swig_intgo arg2, short arg3, swig_voidp arg4);
extern swig_intgo _wrap_airspy_board_id_read_spywrap_c67b9816208bfcb4(uintptr_t arg1, swig_type_9 arg2);
extern swig_intgo _wrap_airspy_version_string_read_spywrap_c67b9816208bfcb4(uintptr_t arg1, swig_type_10 arg2, char arg3);
extern swig_intgo _wrap_airspy_board_partid_serialno_read_spywrap_c67b9816208bfcb4(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_airspy_set_sample_type_spywrap_c67b9816208bfcb4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_airspy_set_freq_spywrap_c67b9816208bfcb4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_airspy_set_lna_gain_spywrap_c67b9816208bfcb4(uintptr_t arg1, char arg2);
extern swig_intgo _wrap_airspy_set_mixer_gain_spywrap_c67b9816208bfcb4(uintptr_t arg1, char arg2);
extern swig_intgo _wrap_airspy_set_vga_gain_spywrap_c67b9816208bfcb4(uintptr_t arg1, char arg2);
extern swig_intgo _wrap_airspy_set_lna_agc_spywrap_c67b9816208bfcb4(uintptr_t arg1, char arg2);
extern swig_intgo _wrap_airspy_set_mixer_agc_spywrap_c67b9816208bfcb4(uintptr_t arg1, char arg2);
extern swig_intgo _wrap_airspy_set_linearity_gain_spywrap_c67b9816208bfcb4(uintptr_t arg1, char arg2);
extern swig_intgo _wrap_airspy_set_sensitivity_gain_spywrap_c67b9816208bfcb4(uintptr_t arg1, char arg2);
extern swig_intgo _wrap_airspy_set_rf_bias_spywrap_c67b9816208bfcb4(uintptr_t arg1, char arg2);
extern swig_intgo _wrap_airspy_set_packing_spywrap_c67b9816208bfcb4(uintptr_t arg1, char arg2);
extern swig_type_11 _wrap_airspy_error_name_spywrap_c67b9816208bfcb4(swig_intgo arg1);
extern swig_type_12 _wrap_airspy_board_id_name_spywrap_c67b9816208bfcb4(swig_intgo arg1);
extern swig_intgo _wrap_airspy_spiflash_erase_sector_spywrap_c67b9816208bfcb4(uintptr_t arg1, short arg2);
extern swig_intgo _wrap_cbProxy_spywrap_c67b9816208bfcb4(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_airspy_open_result_t_device_set_spywrap_c67b9816208bfcb4(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_airspy_open_result_t_device_get_spywrap_c67b9816208bfcb4(uintptr_t arg1);
extern void _wrap_airspy_open_result_t_result_set_spywrap_c67b9816208bfcb4(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_airspy_open_result_t_result_get_spywrap_c67b9816208bfcb4(uintptr_t arg1);
extern uintptr_t _wrap_new_airspy_open_result_t_spywrap_c67b9816208bfcb4(void);
extern void _wrap_delete_airspy_open_result_t_spywrap_c67b9816208bfcb4(uintptr_t arg1);
extern uintptr_t _wrap_openDevice_spywrap_c67b9816208bfcb4(void);
extern uintptr_t _wrap_openDeviceBySerial_spywrap_c67b9816208bfcb4(swig_type_13 arg1);
extern swig_type_14 _wrap_serialNumber_spywrap_c67b9816208bfcb4(swig_voidp arg1);
extern swig_type_15 _wrap_partNumber_spywrap_c67b9816208bfcb4(swig_voidp arg1);
extern void _wrap_freeOpenResult_spywrap_c67b9816208bfcb4(uintptr_t arg1);
extern swig_intgo _wrap_airspyStart_spywrap_c67b9816208bfcb4(uintptr_t arg1, uintptr_t arg2);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"
import "github.com/mattn/go-pointer"

type _ unsafe.Pointer

var Swig_escape_always_false bool
var Swig_escape_val interface{}

type _swig_fnptr *byte
type _swig_memberptr *byte

type _ sync.Mutex

type swig_gostring struct {
	p uintptr
	n int
}

func swigCopyString(s string) string {
	p := *(*swig_gostring)(unsafe.Pointer(&s))
	r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
	Swig_free(p.p)
	return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_spywrap_c67b9816208bfcb4(C.swig_intgo(_swig_i_0)))
	return swig_r
}

const AIRSPY_VERSION string = "1.0.9"
const AIRSPY_VER_MAJOR int = 1
const AIRSPY_VER_MINOR int = 0
const AIRSPY_VER_REVISION int = 9

type Enum_SS_airspy_error int

func _swig_getAIRSPY_SUCCESS() (_swig_ret Enum_SS_airspy_error) {
	var swig_r Enum_SS_airspy_error
	swig_r = (Enum_SS_airspy_error)(C._wrap_AIRSPY_SUCCESS_spywrap_c67b9816208bfcb4())
	return swig_r
}

var AIRSPY_SUCCESS Enum_SS_airspy_error = _swig_getAIRSPY_SUCCESS()

func _swig_getAIRSPY_TRUE() (_swig_ret Enum_SS_airspy_error) {
	var swig_r Enum_SS_airspy_error
	swig_r = (Enum_SS_airspy_error)(C._wrap_AIRSPY_TRUE_spywrap_c67b9816208bfcb4())
	return swig_r
}

var AIRSPY_TRUE Enum_SS_airspy_error = _swig_getAIRSPY_TRUE()

func _swig_getAIRSPY_ERROR_INVALID_PARAM() (_swig_ret Enum_SS_airspy_error) {
	var swig_r Enum_SS_airspy_error
	swig_r = (Enum_SS_airspy_error)(C._wrap_AIRSPY_ERROR_INVALID_PARAM_spywrap_c67b9816208bfcb4())
	return swig_r
}

var AIRSPY_ERROR_INVALID_PARAM Enum_SS_airspy_error = _swig_getAIRSPY_ERROR_INVALID_PARAM()

func _swig_getAIRSPY_ERROR_NOT_FOUND() (_swig_ret Enum_SS_airspy_error) {
	var swig_r Enum_SS_airspy_error
	swig_r = (Enum_SS_airspy_error)(C._wrap_AIRSPY_ERROR_NOT_FOUND_spywrap_c67b9816208bfcb4())
	return swig_r
}

var AIRSPY_ERROR_NOT_FOUND Enum_SS_airspy_error = _swig_getAIRSPY_ERROR_NOT_FOUND()

func _swig_getAIRSPY_ERROR_BUSY() (_swig_ret Enum_SS_airspy_error) {
	var swig_r Enum_SS_airspy_error
	swig_r = (Enum_SS_airspy_error)(C._wrap_AIRSPY_ERROR_BUSY_spywrap_c67b9816208bfcb4())
	return swig_r
}

var AIRSPY_ERROR_BUSY Enum_SS_airspy_error = _swig_getAIRSPY_ERROR_BUSY()

func _swig_getAIRSPY_ERROR_NO_MEM() (_swig_ret Enum_SS_airspy_error) {
	var swig_r Enum_SS_airspy_error
	swig_r = (Enum_SS_airspy_error)(C._wrap_AIRSPY_ERROR_NO_MEM_spywrap_c67b9816208bfcb4())
	return swig_r
}

var AIRSPY_ERROR_NO_MEM Enum_SS_airspy_error = _swig_getAIRSPY_ERROR_NO_MEM()

func _swig_getAIRSPY_ERROR_LIBUSB() (_swig_ret Enum_SS_airspy_error) {
	var swig_r Enum_SS_airspy_error
	swig_r = (Enum_SS_airspy_error)(C._wrap_AIRSPY_ERROR_LIBUSB_spywrap_c67b9816208bfcb4())
	return swig_r
}

var AIRSPY_ERROR_LIBUSB Enum_SS_airspy_error = _swig_getAIRSPY_ERROR_LIBUSB()

func _swig_getAIRSPY_ERROR_THREAD() (_swig_ret Enum_SS_airspy_error) {
	var swig_r Enum_SS_airspy_error
	swig_r = (Enum_SS_airspy_error)(C._wrap_AIRSPY_ERROR_THREAD_spywrap_c67b9816208bfcb4())
	return swig_r
}

var AIRSPY_ERROR_THREAD Enum_SS_airspy_error = _swig_getAIRSPY_ERROR_THREAD()

func _swig_getAIRSPY_ERROR_STREAMING_THREAD_ERR() (_swig_ret Enum_SS_airspy_error) {
	var swig_r Enum_SS_airspy_error
	swig_r = (Enum_SS_airspy_error)(C._wrap_AIRSPY_ERROR_STREAMING_THREAD_ERR_spywrap_c67b9816208bfcb4())
	return swig_r
}

var AIRSPY_ERROR_STREAMING_THREAD_ERR Enum_SS_airspy_error = _swig_getAIRSPY_ERROR_STREAMING_THREAD_ERR()

func _swig_getAIRSPY_ERROR_STREAMING_STOPPED() (_swig_ret Enum_SS_airspy_error) {
	var swig_r Enum_SS_airspy_error
	swig_r = (Enum_SS_airspy_error)(C._wrap_AIRSPY_ERROR_STREAMING_STOPPED_spywrap_c67b9816208bfcb4())
	return swig_r
}

var AIRSPY_ERROR_STREAMING_STOPPED Enum_SS_airspy_error = _swig_getAIRSPY_ERROR_STREAMING_STOPPED()

func _swig_getAIRSPY_ERROR_OTHER() (_swig_ret Enum_SS_airspy_error) {
	var swig_r Enum_SS_airspy_error
	swig_r = (Enum_SS_airspy_error)(C._wrap_AIRSPY_ERROR_OTHER_spywrap_c67b9816208bfcb4())
	return swig_r
}

var AIRSPY_ERROR_OTHER Enum_SS_airspy_error = _swig_getAIRSPY_ERROR_OTHER()

type Enum_SS_airspy_board_id int

func _swig_getAIRSPY_BOARD_ID_PROTO_AIRSPY() (_swig_ret Enum_SS_airspy_board_id) {
	var swig_r Enum_SS_airspy_board_id
	swig_r = (Enum_SS_airspy_board_id)(C._wrap_AIRSPY_BOARD_ID_PROTO_AIRSPY_spywrap_c67b9816208bfcb4())
	return swig_r
}

var AIRSPY_BOARD_ID_PROTO_AIRSPY Enum_SS_airspy_board_id = _swig_getAIRSPY_BOARD_ID_PROTO_AIRSPY()

func _swig_getAIRSPY_BOARD_ID_INVALID() (_swig_ret Enum_SS_airspy_board_id) {
	var swig_r Enum_SS_airspy_board_id
	swig_r = (Enum_SS_airspy_board_id)(C._wrap_AIRSPY_BOARD_ID_INVALID_spywrap_c67b9816208bfcb4())
	return swig_r
}

var AIRSPY_BOARD_ID_INVALID Enum_SS_airspy_board_id = _swig_getAIRSPY_BOARD_ID_INVALID()

type Enum_SS_airspy_sample_type int

func _swig_getAIRSPY_SAMPLE_FLOAT32_IQ() (_swig_ret Enum_SS_airspy_sample_type) {
	var swig_r Enum_SS_airspy_sample_type
	swig_r = (Enum_SS_airspy_sample_type)(C._wrap_AIRSPY_SAMPLE_FLOAT32_IQ_spywrap_c67b9816208bfcb4())
	return swig_r
}

var AIRSPY_SAMPLE_FLOAT32_IQ Enum_SS_airspy_sample_type = _swig_getAIRSPY_SAMPLE_FLOAT32_IQ()

func _swig_getAIRSPY_SAMPLE_FLOAT32_REAL() (_swig_ret Enum_SS_airspy_sample_type) {
	var swig_r Enum_SS_airspy_sample_type
	swig_r = (Enum_SS_airspy_sample_type)(C._wrap_AIRSPY_SAMPLE_FLOAT32_REAL_spywrap_c67b9816208bfcb4())
	return swig_r
}

var AIRSPY_SAMPLE_FLOAT32_REAL Enum_SS_airspy_sample_type = _swig_getAIRSPY_SAMPLE_FLOAT32_REAL()

func _swig_getAIRSPY_SAMPLE_INT16_IQ() (_swig_ret Enum_SS_airspy_sample_type) {
	var swig_r Enum_SS_airspy_sample_type
	swig_r = (Enum_SS_airspy_sample_type)(C._wrap_AIRSPY_SAMPLE_INT16_IQ_spywrap_c67b9816208bfcb4())
	return swig_r
}

var AIRSPY_SAMPLE_INT16_IQ Enum_SS_airspy_sample_type = _swig_getAIRSPY_SAMPLE_INT16_IQ()

func _swig_getAIRSPY_SAMPLE_INT16_REAL() (_swig_ret Enum_SS_airspy_sample_type) {
	var swig_r Enum_SS_airspy_sample_type
	swig_r = (Enum_SS_airspy_sample_type)(C._wrap_AIRSPY_SAMPLE_INT16_REAL_spywrap_c67b9816208bfcb4())
	return swig_r
}

var AIRSPY_SAMPLE_INT16_REAL Enum_SS_airspy_sample_type = _swig_getAIRSPY_SAMPLE_INT16_REAL()

func _swig_getAIRSPY_SAMPLE_UINT16_REAL() (_swig_ret Enum_SS_airspy_sample_type) {
	var swig_r Enum_SS_airspy_sample_type
	swig_r = (Enum_SS_airspy_sample_type)(C._wrap_AIRSPY_SAMPLE_UINT16_REAL_spywrap_c67b9816208bfcb4())
	return swig_r
}

var AIRSPY_SAMPLE_UINT16_REAL Enum_SS_airspy_sample_type = _swig_getAIRSPY_SAMPLE_UINT16_REAL()

func _swig_getAIRSPY_SAMPLE_RAW() (_swig_ret Enum_SS_airspy_sample_type) {
	var swig_r Enum_SS_airspy_sample_type
	swig_r = (Enum_SS_airspy_sample_type)(C._wrap_AIRSPY_SAMPLE_RAW_spywrap_c67b9816208bfcb4())
	return swig_r
}

var AIRSPY_SAMPLE_RAW Enum_SS_airspy_sample_type = _swig_getAIRSPY_SAMPLE_RAW()

func _swig_getAIRSPY_SAMPLE_END() (_swig_ret Enum_SS_airspy_sample_type) {
	var swig_r Enum_SS_airspy_sample_type
	swig_r = (Enum_SS_airspy_sample_type)(C._wrap_AIRSPY_SAMPLE_END_spywrap_c67b9816208bfcb4())
	return swig_r
}

var AIRSPY_SAMPLE_END Enum_SS_airspy_sample_type = _swig_getAIRSPY_SAMPLE_END()

func _swig_getMAX_CONFIG_PAGE_SIZE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_MAX_CONFIG_PAGE_SIZE_spywrap_c67b9816208bfcb4())
	return swig_r
}

var MAX_CONFIG_PAGE_SIZE int = _swig_getMAX_CONFIG_PAGE_SIZE()

type SwigcptrAirspy_transfer_t uintptr

func (p SwigcptrAirspy_transfer_t) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrAirspy_transfer_t) SwigIsAirspy_transfer_t() {
}

func (arg1 SwigcptrAirspy_transfer_t) SetDevice(arg2 Struct_SS_airspy_device) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_airspy_transfer_t_device_set_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrAirspy_transfer_t) GetDevice() (_swig_ret Struct_SS_airspy_device) {
	var swig_r Struct_SS_airspy_device
	_swig_i_0 := arg1
	swig_r = (Struct_SS_airspy_device)(SwigcptrStruct_SS_airspy_device(C._wrap_airspy_transfer_t_device_get_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrAirspy_transfer_t) SetCtx(arg2 uintptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_airspy_transfer_t_ctx_set_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrAirspy_transfer_t) GetCtx() (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_airspy_transfer_t_ctx_get_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrAirspy_transfer_t) SetSamples(arg2 uintptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_airspy_transfer_t_samples_set_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrAirspy_transfer_t) GetSamples() (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_airspy_transfer_t_samples_get_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrAirspy_transfer_t) SetSample_count(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_airspy_transfer_t_sample_count_set_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrAirspy_transfer_t) GetSample_count() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_airspy_transfer_t_sample_count_get_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrAirspy_transfer_t) SetDropped_samples(arg2 uint64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_airspy_transfer_t_dropped_samples_set_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.swig_type_1(_swig_i_1))
}

func (arg1 SwigcptrAirspy_transfer_t) GetDropped_samples() (_swig_ret uint64) {
	var swig_r uint64
	_swig_i_0 := arg1
	swig_r = (uint64)(C._wrap_airspy_transfer_t_dropped_samples_get_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrAirspy_transfer_t) SetSample_type(arg2 Enum_SS_airspy_sample_type) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_airspy_transfer_t_sample_type_set_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrAirspy_transfer_t) GetSample_type() (_swig_ret Enum_SS_airspy_sample_type) {
	var swig_r Enum_SS_airspy_sample_type
	_swig_i_0 := arg1
	swig_r = (Enum_SS_airspy_sample_type)(C._wrap_airspy_transfer_t_sample_type_get_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewAirspy_transfer_t() (_swig_ret Airspy_transfer_t) {
	var swig_r Airspy_transfer_t
	swig_r = (Airspy_transfer_t)(SwigcptrAirspy_transfer_t(C._wrap_new_airspy_transfer_t_spywrap_c67b9816208bfcb4()))
	return swig_r
}

func DeleteAirspy_transfer_t(arg1 Airspy_transfer_t) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_airspy_transfer_t_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0))
}

type Airspy_transfer_t interface {
	Swigcptr() uintptr
	SwigIsAirspy_transfer_t()
	SetDevice(arg2 Struct_SS_airspy_device)
	GetDevice() (_swig_ret Struct_SS_airspy_device)
	SetCtx(arg2 uintptr)
	GetCtx() (_swig_ret uintptr)
	SetSamples(arg2 uintptr)
	GetSamples() (_swig_ret uintptr)
	SetSample_count(arg2 int)
	GetSample_count() (_swig_ret int)
	SetDropped_samples(arg2 uint64)
	GetDropped_samples() (_swig_ret uint64)
	SetSample_type(arg2 Enum_SS_airspy_sample_type)
	GetSample_type() (_swig_ret Enum_SS_airspy_sample_type)
}

type SwigcptrAirspy_read_partid_serialno_t uintptr

func (p SwigcptrAirspy_read_partid_serialno_t) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrAirspy_read_partid_serialno_t) SwigIsAirspy_read_partid_serialno_t() {
}

func (arg1 SwigcptrAirspy_read_partid_serialno_t) SetPart_id(arg2 *uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_airspy_read_partid_serialno_t_part_id_set_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrAirspy_read_partid_serialno_t) GetPart_id() (_swig_ret *uint) {
	var swig_r *uint
	_swig_i_0 := arg1
	swig_r = (*uint)(C._wrap_airspy_read_partid_serialno_t_part_id_get_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrAirspy_read_partid_serialno_t) SetSerial_no(arg2 *uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_airspy_read_partid_serialno_t_serial_no_set_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrAirspy_read_partid_serialno_t) GetSerial_no() (_swig_ret *uint) {
	var swig_r *uint
	_swig_i_0 := arg1
	swig_r = (*uint)(C._wrap_airspy_read_partid_serialno_t_serial_no_get_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewAirspy_read_partid_serialno_t() (_swig_ret Airspy_read_partid_serialno_t) {
	var swig_r Airspy_read_partid_serialno_t
	swig_r = (Airspy_read_partid_serialno_t)(SwigcptrAirspy_read_partid_serialno_t(C._wrap_new_airspy_read_partid_serialno_t_spywrap_c67b9816208bfcb4()))
	return swig_r
}

func DeleteAirspy_read_partid_serialno_t(arg1 Airspy_read_partid_serialno_t) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_airspy_read_partid_serialno_t_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0))
}

type Airspy_read_partid_serialno_t interface {
	Swigcptr() uintptr
	SwigIsAirspy_read_partid_serialno_t()
	SetPart_id(arg2 *uint)
	GetPart_id() (_swig_ret *uint)
	SetSerial_no(arg2 *uint)
	GetSerial_no() (_swig_ret *uint)
}

type SwigcptrAirspy_lib_version_t uintptr

func (p SwigcptrAirspy_lib_version_t) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrAirspy_lib_version_t) SwigIsAirspy_lib_version_t() {
}

func (arg1 SwigcptrAirspy_lib_version_t) SetMajor_version(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_airspy_lib_version_t_major_version_set_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrAirspy_lib_version_t) GetMajor_version() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_airspy_lib_version_t_major_version_get_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrAirspy_lib_version_t) SetMinor_version(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_airspy_lib_version_t_minor_version_set_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrAirspy_lib_version_t) GetMinor_version() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_airspy_lib_version_t_minor_version_get_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrAirspy_lib_version_t) SetRevision(arg2 uint) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_airspy_lib_version_t_revision_set_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrAirspy_lib_version_t) GetRevision() (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_airspy_lib_version_t_revision_get_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewAirspy_lib_version_t() (_swig_ret Airspy_lib_version_t) {
	var swig_r Airspy_lib_version_t
	swig_r = (Airspy_lib_version_t)(SwigcptrAirspy_lib_version_t(C._wrap_new_airspy_lib_version_t_spywrap_c67b9816208bfcb4()))
	return swig_r
}

func DeleteAirspy_lib_version_t(arg1 Airspy_lib_version_t) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_airspy_lib_version_t_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0))
}

type Airspy_lib_version_t interface {
	Swigcptr() uintptr
	SwigIsAirspy_lib_version_t()
	SetMajor_version(arg2 uint)
	GetMajor_version() (_swig_ret uint)
	SetMinor_version(arg2 uint)
	GetMinor_version() (_swig_ret uint)
	SetRevision(arg2 uint)
	GetRevision() (_swig_ret uint)
}

func Airspy_lib_version(arg1 Airspy_lib_version_t) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_airspy_lib_version_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0))
}

func Airspy_init() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_airspy_init_spywrap_c67b9816208bfcb4())
	return swig_r
}

func Airspy_exit() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_airspy_exit_spywrap_c67b9816208bfcb4())
	return swig_r
}

func Airspy_open_sn(arg1 Struct_SS_airspy_device, arg2 uint64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_airspy_open_sn_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.swig_type_3(_swig_i_1)))
	return swig_r
}

func Airspy_open(arg1 Struct_SS_airspy_device) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_airspy_open_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Airspy_close(arg1 Struct_SS_airspy_device) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_airspy_close_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Airspy_get_samplerates(arg1 Struct_SS_airspy_device, arg2 []uint32, arg3 uint) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_airspy_get_samplerates_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), *(*C.swig_type_4)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Airspy_set_samplerate(arg1 Struct_SS_airspy_device, arg2 uint) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_airspy_set_samplerate_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Airspy_set_conversion_filter_float32(arg1 Struct_SS_airspy_device, arg2 *float32, arg3 uint) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_airspy_set_conversion_filter_float32_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func Airspy_set_conversion_filter_int16(arg1 Struct_SS_airspy_device, arg2 *int16, arg3 uint) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_airspy_set_conversion_filter_int16_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func Airspy_start_rx(arg1 Struct_SS_airspy_device, arg2 *_swig_fnptr, arg3 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_airspy_start_rx_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func Airspy_stop_rx(arg1 Struct_SS_airspy_device) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_airspy_stop_rx_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Airspy_is_streaming(arg1 Struct_SS_airspy_device) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_airspy_is_streaming_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Airspy_si5351c_write(arg1 Struct_SS_airspy_device, arg2 byte, arg3 byte) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_airspy_si5351c_write_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.char(_swig_i_1), C.char(_swig_i_2)))
	return swig_r
}

func Airspy_si5351c_read(arg1 Struct_SS_airspy_device, arg2 byte, arg3 []byte) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_airspy_si5351c_read_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.char(_swig_i_1), *(*C.swig_type_5)(unsafe.Pointer(&_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func Airspy_r820t_write(arg1 Struct_SS_airspy_device, arg2 byte, arg3 byte) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_airspy_r820t_write_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.char(_swig_i_1), C.char(_swig_i_2)))
	return swig_r
}

func Airspy_r820t_read(arg1 Struct_SS_airspy_device, arg2 byte, arg3 []byte) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_airspy_r820t_read_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.char(_swig_i_1), *(*C.swig_type_6)(unsafe.Pointer(&_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func Airspy_gpio_write(arg1 Struct_SS_airspy_device, arg2 Airspy_gpio_port_t, arg3 Airspy_gpio_pin_t, arg4 byte) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_airspy_gpio_write_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.char(_swig_i_3)))
	return swig_r
}

func Airspy_gpio_read(arg1 Struct_SS_airspy_device, arg2 Airspy_gpio_port_t, arg3 Airspy_gpio_pin_t, arg4 []byte) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_airspy_gpio_read_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), *(*C.swig_type_7)(unsafe.Pointer(&_swig_i_3))))
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
	return swig_r
}

func Airspy_gpiodir_write(arg1 Struct_SS_airspy_device, arg2 Airspy_gpio_port_t, arg3 Airspy_gpio_pin_t, arg4 byte) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_airspy_gpiodir_write_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.char(_swig_i_3)))
	return swig_r
}

func Airspy_gpiodir_read(arg1 Struct_SS_airspy_device, arg2 Airspy_gpio_port_t, arg3 Airspy_gpio_pin_t, arg4 []byte) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_airspy_gpiodir_read_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), *(*C.swig_type_8)(unsafe.Pointer(&_swig_i_3))))
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
	return swig_r
}

func Airspy_spiflash_erase(arg1 Struct_SS_airspy_device) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_airspy_spiflash_erase_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Airspy_spiflash_write(arg1 Struct_SS_airspy_device, arg2 uint, arg3 uint16, arg4 *byte) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_airspy_spiflash_write_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.short(_swig_i_2), C.swig_voidp(_swig_i_3)))
	return swig_r
}

func Airspy_spiflash_read(arg1 Struct_SS_airspy_device, arg2 uint, arg3 uint16, arg4 *byte) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_airspy_spiflash_read_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.short(_swig_i_2), C.swig_voidp(_swig_i_3)))
	return swig_r
}

func Airspy_board_id_read(arg1 Struct_SS_airspy_device, arg2 []byte) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_airspy_board_id_read_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), *(*C.swig_type_9)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Airspy_version_string_read(arg1 Struct_SS_airspy_device, arg2 []byte, arg3 byte) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_airspy_version_string_read_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), *(*C.swig_type_10)(unsafe.Pointer(&_swig_i_1)), C.char(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Airspy_board_partid_serialno_read(arg1 Struct_SS_airspy_device, arg2 Airspy_read_partid_serialno_t) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int)(C._wrap_airspy_board_partid_serialno_read_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Airspy_set_sample_type(arg1 Struct_SS_airspy_device, arg2 Enum_SS_airspy_sample_type) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_airspy_set_sample_type_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Airspy_set_freq(arg1 Struct_SS_airspy_device, arg2 uint) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_airspy_set_freq_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Airspy_set_lna_gain(arg1 Struct_SS_airspy_device, arg2 byte) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_airspy_set_lna_gain_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.char(_swig_i_1)))
	return swig_r
}

func Airspy_set_mixer_gain(arg1 Struct_SS_airspy_device, arg2 byte) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_airspy_set_mixer_gain_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.char(_swig_i_1)))
	return swig_r
}

func Airspy_set_vga_gain(arg1 Struct_SS_airspy_device, arg2 byte) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_airspy_set_vga_gain_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.char(_swig_i_1)))
	return swig_r
}

func Airspy_set_lna_agc(arg1 Struct_SS_airspy_device, arg2 byte) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_airspy_set_lna_agc_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.char(_swig_i_1)))
	return swig_r
}

func Airspy_set_mixer_agc(arg1 Struct_SS_airspy_device, arg2 byte) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_airspy_set_mixer_agc_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.char(_swig_i_1)))
	return swig_r
}

func Airspy_set_linearity_gain(arg1 Struct_SS_airspy_device, arg2 byte) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_airspy_set_linearity_gain_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.char(_swig_i_1)))
	return swig_r
}

func Airspy_set_sensitivity_gain(arg1 Struct_SS_airspy_device, arg2 byte) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_airspy_set_sensitivity_gain_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.char(_swig_i_1)))
	return swig_r
}

func Airspy_set_rf_bias(arg1 Struct_SS_airspy_device, arg2 byte) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_airspy_set_rf_bias_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.char(_swig_i_1)))
	return swig_r
}

func Airspy_set_packing(arg1 Struct_SS_airspy_device, arg2 byte) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_airspy_set_packing_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.char(_swig_i_1)))
	return swig_r
}

func Airspy_error_name(arg1 Enum_SS_airspy_error) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_airspy_error_name_spywrap_c67b9816208bfcb4(C.swig_intgo(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func Airspy_board_id_name(arg1 Enum_SS_airspy_board_id) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_airspy_board_id_name_spywrap_c67b9816208bfcb4(C.swig_intgo(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func Airspy_spiflash_erase_sector(arg1 Struct_SS_airspy_device, arg2 uint16) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_airspy_spiflash_erase_sector_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.short(_swig_i_1)))
	return swig_r
}

func CbProxy(arg1 uintptr, arg2 Airspy_transfer_t) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int)(C._wrap_cbProxy_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

type SwigcptrAirspy_open_result_t uintptr

func (p SwigcptrAirspy_open_result_t) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrAirspy_open_result_t) SwigIsAirspy_open_result_t() {
}

func (arg1 SwigcptrAirspy_open_result_t) SetDevice(arg2 Struct_SS_airspy_device) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_airspy_open_result_t_device_set_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrAirspy_open_result_t) GetDevice() (_swig_ret Struct_SS_airspy_device) {
	var swig_r Struct_SS_airspy_device
	_swig_i_0 := arg1
	swig_r = (Struct_SS_airspy_device)(SwigcptrStruct_SS_airspy_device(C._wrap_airspy_open_result_t_device_get_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrAirspy_open_result_t) SetResult(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_airspy_open_result_t_result_set_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrAirspy_open_result_t) GetResult() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_airspy_open_result_t_result_get_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewAirspy_open_result_t() (_swig_ret Airspy_open_result_t) {
	var swig_r Airspy_open_result_t
	swig_r = (Airspy_open_result_t)(SwigcptrAirspy_open_result_t(C._wrap_new_airspy_open_result_t_spywrap_c67b9816208bfcb4()))
	return swig_r
}

func DeleteAirspy_open_result_t(arg1 Airspy_open_result_t) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_airspy_open_result_t_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0))
}

type Airspy_open_result_t interface {
	Swigcptr() uintptr
	SwigIsAirspy_open_result_t()
	SetDevice(arg2 Struct_SS_airspy_device)
	GetDevice() (_swig_ret Struct_SS_airspy_device)
	SetResult(arg2 int)
	GetResult() (_swig_ret int)
}

func OpenDevice() (_swig_ret Airspy_open_result_t) {
	var swig_r Airspy_open_result_t
	swig_r = (Airspy_open_result_t)(SwigcptrAirspy_open_result_t(C._wrap_openDevice_spywrap_c67b9816208bfcb4()))
	return swig_r
}

func OpenDeviceBySerial(arg1 uint64) (_swig_ret Airspy_open_result_t) {
	var swig_r Airspy_open_result_t
	_swig_i_0 := arg1
	swig_r = (Airspy_open_result_t)(SwigcptrAirspy_open_result_t(C._wrap_openDeviceBySerial_spywrap_c67b9816208bfcb4(C.swig_type_13(_swig_i_0))))
	return swig_r
}

func SerialNumber(arg1 *uint) (_swig_ret uint64) {
	var swig_r uint64
	_swig_i_0 := arg1
	swig_r = (uint64)(C._wrap_serialNumber_spywrap_c67b9816208bfcb4(C.swig_voidp(_swig_i_0)))
	return swig_r
}

func PartNumber(arg1 *uint) (_swig_ret uint64) {
	var swig_r uint64
	_swig_i_0 := arg1
	swig_r = (uint64)(C._wrap_partNumber_spywrap_c67b9816208bfcb4(C.swig_voidp(_swig_i_0)))
	return swig_r
}

func FreeOpenResult(arg1 Airspy_open_result_t) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_freeOpenResult_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0))
}

func AirspyStart(arg1 Struct_SS_airspy_device, arg2 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_airspyStart_spywrap_c67b9816208bfcb4(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

type Callback struct {
	Func func(interface{}, Airspy_transfer_t) int
	Data interface{}
}

//export cbProxy
func cbProxy(v unsafe.Pointer, d SwigcptrAirspy_transfer_t) int {
	cb := pointer.Restore(v).(*Callback)
	return cb.Func(cb.Data, d)
}

type SwigcptrAirspy_gpio_pin_t uintptr
type Airspy_gpio_pin_t interface {
	Swigcptr() uintptr
}

func (p SwigcptrAirspy_gpio_pin_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrAirspy_gpio_port_t uintptr
type Airspy_gpio_port_t interface {
	Swigcptr() uintptr
}

func (p SwigcptrAirspy_gpio_port_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStruct_SS_airspy_device uintptr
type Struct_SS_airspy_device interface {
	Swigcptr() uintptr
}

func (p SwigcptrStruct_SS_airspy_device) Swigcptr() uintptr {
	return uintptr(p)
}
